[package]
name = "remote-ops-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
if-addrs.workspace = true
libc.workspace = true
remote-ops-protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Wdk_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_JobObjects",
    "Win32_System_Memory",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
] }

[dev-dependencies]
tempfile.workspace = true
